### ISSUE TITLE
Clicking languages displays percentages.

### ISSUE THREAD

**Issue by Atlasx** [KyroChi/GitHub-Profile-Fluency#20]
This would be an excellent feature to add.

**Comment by phase** [comment]
The percentages are already shown next to the language,
![languages](http://i.imgur.com/E02Keoh.png)
Unless you are talking about something else

**Comment by KyroChi** [comment]
He's talking about clicking the word "languages" in the bar to pull up the language display info. We found that people intuitively click "languages" and as it was nothing would happen. We have added this feature and I will update it on the chrome store soon. Update your development version if you want to see the changes immediately :)
