### ISSUE TITLE
Nothing visible after installing extension

### ISSUE THREAD

**Issue by ghost** [KyroChi/GitHub-Profile-Fluency#24]
Possibly useful information - 
Re-added to Chrome. Same result.
Allowed in inconito. Same result.

**Comment by KyroChi** [comment]
I think this happened when chrome updated, a similar thing happened a few months ago. I will look into it this weekend and see if I can get a fix out :)

**Comment by KyroChi** [comment]
Hey sorry that took so long, I have been very busy as of late, I pushed 4590206 which fixes this issue and pushed the updated version to the chrome web store.
