### ISSUE TITLE
Add Firefox addon to the Firefox explore site

### ISSUE THREAD

**Issue by aleclarson** [KyroChi/GitHub-Profile-Fluency#26]
https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=github+profile+fluency

**Comment by KyroChi** [comment]
There is no Firefox version of the extension... sorry :(

**Comment by aleclarson** [comment]
@KyroChi Have you taken a look at Firefox Quantum yet? I wonder if the addon API has improved enough that you would want to make d9d0ab92db4edbc7de8bead2962b8f2370b03a58 work again. 😀

**Comment by KyroChi** [comment]
@aleclarson I have not, did not realize they had updated the API! I will take a look when I have some free time and see if the development is less frustrating this time around :)
