### ISSUE TITLE
Display "Other" Language if user has more than 7 languages

### ISSUE THREAD

**Issue by KyroChi** [KyroChi/GitHub-Profile-Fluency#3]
Currently the number of listed languages is capped at 7. The counter still reads accurately. Improve so that the languages will have an "Other" section to display the remaining languages.

Languages will be scaled so that the number displayed changes based on the length of the language names so that languages do not spill out of the counter.

**Comment by acwaters** [comment]
Hey, I wrote up something that takes care of this issue; I can submit a PR for you to take a look at it if you like.

**Comment by KyroChi** [comment]
Please do!! It would be much appreciated!!

Edit: Looked over your code and there are a few modifications I would suggest you make, first, maybe include 5 languages + the other language to give a better range (eventually I would like to make it so that it fits the maximum amount of languages horizontally that the space allows, but that is a challenge for another day) Second, the "other" section displays the color of the last language instead of "#ededed" like the repository graphs show. Other than that this looks like a great addition and I can't wait to merge your PR!

`320:    span_color.style.backgroundColor = "#ededed";`
`339:    span_language_color.style.backgroundColor = "#ededed";`

**Comment by acwaters** [comment]
Ah, thanks! Yeah, the color was an oversight. The number I made adjustable pending a dynamic solution, and I was moving it up and down for purposes of testing. I'll fix those and submit.

**Comment by KyroChi** [comment]
closed by #19
