### ISSUE TITLE
Ignore Forked Repositories

### ISSUE THREAD

**Issue by umayr** [KyroChi/GitHub-Profile-Fluency#5]
<img width="740" alt="screen shot 2015-09-06 at 14 26 56" src="https://cloud.githubusercontent.com/assets/3071948/9703632/64d24d9c-54a3-11e5-85c7-6ddd8d3b5f12.png">

As seen in the image above, it shows that Dart is my most fluent language which is not the case. It is only due to the reason I have forked this [repo](https://github.com/umayr/dart-samples). (I don't think I have any other dart repo.)

So, in order to get it working properly, ignore all forks perhaps?

**Comment by umayr** [comment]
Duplicate of #2.

Closing it.

**Comment by KyroChi** [comment]
![image](http://i.imgur.com/qib8h6M.png)

This is a temporary fix of a much bigger problem, I am ignoring forks, but not the languages of those forks in the most recent update of content.js.

If you would like to use this version until I update the extension in the chrome webstore you can download the repository and load it in chrome as an unpacked development extension.

I will eventually try and solve the greater problems addressed in #5 and get much more accurate information :)
